name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint code
        run: |
          flake8 src/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest src/test_model.py

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: SSH and Deploy
        if: success()
        env:
          KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_PRIVATE_KEY }} ec2-user@16.170.248.183 << 'EOF'
          cd /home/ec2-user/liver-app
          pip install -r requirements.txt
          nohup python3 /home/ec2-user/liver-app/app/liver_app.py &
          EOF