name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint code
        run: |
          flake8 src/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest src/test_model.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy deploy script to EC2
        run: |
          scp -o StrictHostKeyChecking=no deploy.sh ec2-user@16.171.44.242:/home/ec2-user/

      - name: SSH into EC2 and run deploy script
        run: |
          ssh -o StrictHostKeyChecking=no -i /home/ec2-user/liver-server-key.pem ec2-user@16.171.44.242 << 'EOF'
          chmod +x /home/ec2-user/deploy.sh
          /home/ec2-user/deploy.sh
          EOF